apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: "not-applicable"
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - name: http
              protocol: TCP
              containerPort: 15672
            - name: amqp
              protocol: TCP
              containerPort: 5672
          envFrom:
            - configMapRef:
                name: rabbitmq-configmap
            - secretRef:
                name: rabbitmq-secret
          env:
            - name: RABBITMQ_LOAD_DEFINITIONS
              value: "/etc/rabbitmq/definitions.json"
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-volume
            - mountPath: /etc/rabbitmq/definitions.json
              name: rabbitmq-definitions
              subPath: definitions.json
      volumes:
        - name: rabbitmq-volume
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
        - name: rabbitmq-definitions
          configMap:
            name: rabbitmq-definitions
